import type { AuditLogAction } from "@/types";

export const actionLabels: Record<AuditLogAction, string> = {
  user_login: "User Login",
  user_logout: "User Logout",
  password_reset: "Password Reset",
  user_created: "User Created",
  user_updated: "User Updated",
  user_deleted: "User Deleted",
  role_changed: "Role Changed",
  camera_added: "Camera Added",
  camera_updated: "Camera Updated",
  camera_deleted: "Camera Deleted",
  camera_started: "Camera Started",
  camera_stopped: "Camera Stopped",
  ai_model_enabled: "AI Model Enabled",
  ai_model_disabled: "AI Model Disabled",
  ai_model_updated: "AI Model Updated",
  detection_created: "Detection Created",
  alert_created: "Alert Created",
  report_generated: "Report Generated",
  settings_changed: "Settings Changed",
};

export const actionStyles: Record<AuditLogAction, { bg: string; text: string; border: string }> = {
  user_login: { bg: "bg-blue-50", text: "text-blue-700", border: "border-blue-200" },
  user_logout: { bg: "bg-slate-100", text: "text-slate-700", border: "border-slate-200" },
  password_reset: { bg: "bg-violet-50", text: "text-violet-700", border: "border-violet-200" },
  user_created: { bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200" },
  user_updated: { bg: "bg-cyan-50", text: "text-cyan-700", border: "border-cyan-200" },
  user_deleted: { bg: "bg-red-50", text: "text-red-700", border: "border-red-200" },
  role_changed: { bg: "bg-amber-50", text: "text-amber-700", border: "border-amber-200" },
  camera_added: { bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200" },
  camera_updated: { bg: "bg-cyan-50", text: "text-cyan-700", border: "border-cyan-200" },
  camera_deleted: { bg: "bg-red-50", text: "text-red-700", border: "border-red-200" },
  camera_started: { bg: "bg-green-50", text: "text-green-700", border: "border-green-200" },
  camera_stopped: { bg: "bg-orange-50", text: "text-orange-700", border: "border-orange-200" },
  ai_model_enabled: { bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200" },
  ai_model_disabled: { bg: "bg-orange-50", text: "text-orange-700", border: "border-orange-200" },
  ai_model_updated: { bg: "bg-indigo-50", text: "text-indigo-700", border: "border-indigo-200" },
  detection_created: { bg: "bg-teal-50", text: "text-teal-700", border: "border-teal-200" },
  alert_created: { bg: "bg-rose-50", text: "text-rose-700", border: "border-rose-200" },
  report_generated: { bg: "bg-purple-50", text: "text-purple-700", border: "border-purple-200" },
  settings_changed: { bg: "bg-gray-100", text: "text-gray-700", border: "border-gray-200" },
};
