import { registerDetector, type DetectorDefinition } from "./registry";

/**
 * Default detector catalogue.
 *
 * `availability` is NOT decorative: only detectors with a real trained
 * model available (currently `person` and `vehicle`, both backed by the
 * YOLOv11 COCO model) are marked `available`. Every other detector is
 * registered as `unconfigured` so its configuration, lifecycle and
 * status can be managed, but the engine refuses to fabricate inference
 * results until a real model is installed.
 */
export const defaultDetectorDefinitions: DetectorDefinition[] = [
  {
    key: "person",
    name: "Person Detection",
    version: "1.0.0",
    description: "Detects persons in camera frames using YOLOv11.",
    category: "Person",
    icon: "person",
    type: "object_detection",
    availability: "available",
    supportedInput: ["image", "video", "webcam"],
    defaultConfidenceThreshold: 50,
    gpuSupported: true,
    modelPath: "/models/person/yolo11n.pt",
    inferenceTimeMs: 24,
    classFilter: ["person"],
    defaultConfiguration: {
      detectionIntervalMs: 1000,
      maxDetectionsPerFrame: 20,
      alertSeverity: "info",
      alertCooldownMs: 30000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: true,
  },
  {
    key: "vehicle",
    name: "Vehicle Detection",
    version: "1.0.0",
    description: "Detects cars, trucks, buses and motorcycles in traffic zones.",
    category: "Vehicle",
    icon: "vehicle",
    type: "object_detection",
    availability: "available",
    supportedInput: ["image", "video", "webcam"],
    defaultConfidenceThreshold: 50,
    gpuSupported: true,
    modelPath: "/models/vehicle/yolo11n.pt",
    inferenceTimeMs: 34,
    classFilter: ["car", "truck", "bus", "motorcycle"],
    defaultConfiguration: {
      detectionIntervalMs: 2000,
      maxDetectionsPerFrame: 20,
      alertSeverity: "info",
      alertCooldownMs: 60000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: true,
  },
  {
    key: "fire",
    name: "Fire Detection",
    version: "1.0.0",
    description: "Detects fire and open flames in monitored areas.",
    category: "Fire",
    icon: "fire",
    type: "object_detection",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 45,
    gpuSupported: true,
    modelPath: "/models/fire/fire.pt",
    inferenceTimeMs: 30,
    defaultConfiguration: {
      detectionIntervalMs: 2000,
      maxDetectionsPerFrame: 10,
      alertSeverity: "critical",
      alertCooldownMs: 15000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: true,
  },
  {
    key: "smoking",
    name: "Smoking Detection",
    version: "1.0.0",
    description: "Detects smoking activity in restricted areas.",
    category: "Behavior",
    icon: "smoking",
    type: "object_detection",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 55,
    gpuSupported: true,
    modelPath: "/models/smoking/smoking.pt",
    inferenceTimeMs: 38,
    defaultConfiguration: {
      detectionIntervalMs: 2000,
      maxDetectionsPerFrame: 10,
      alertSeverity: "warning",
      alertCooldownMs: 30000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: true,
  },
  {
    key: "helmet",
    name: "Helmet Detection",
    version: "1.0.0",
    description: "Detects workers without protective helmets.",
    category: "Safety",
    icon: "helmet",
    type: "object_detection",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 60,
    gpuSupported: true,
    modelPath: "/models/helmet/helmet.pt",
    inferenceTimeMs: 32,
    defaultConfiguration: {
      detectionIntervalMs: 2000,
      maxDetectionsPerFrame: 15,
      alertSeverity: "warning",
      alertCooldownMs: 30000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: true,
  },
  {
    key: "face_mask",
    name: "Face Mask Detection",
    version: "1.0.0",
    description: "Detects persons without face masks in restricted zones.",
    category: "Safety",
    icon: "face-mask",
    type: "object_detection",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 55,
    gpuSupported: true,
    modelPath: "/models/face_mask/face_mask.pt",
    inferenceTimeMs: 26,
    defaultConfiguration: {
      detectionIntervalMs: 2000,
      maxDetectionsPerFrame: 10,
      alertSeverity: "warning",
      alertCooldownMs: 30000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: true,
  },
  {
    key: "intrusion",
    name: "Intrusion Detection",
    version: "1.0.0",
    description: "Detects unauthorized entry into restricted zones.",
    category: "Security",
    icon: "intrusion",
    type: "object_detection",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 65,
    gpuSupported: true,
    modelPath: "/models/intrusion/intrusion.pt",
    inferenceTimeMs: 40,
    defaultConfiguration: {
      detectionIntervalMs: 1500,
      maxDetectionsPerFrame: 10,
      alertSeverity: "critical",
      alertCooldownMs: 20000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: true,
  },
  {
    key: "drowsiness",
    name: "Drowsiness Detection",
    version: "1.0.0",
    description: "Detects operator drowsiness and fatigue signs.",
    category: "Behavior",
    icon: "drowsiness",
    type: "classification",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 60,
    gpuSupported: true,
    modelPath: "/models/drowsiness/drowsiness.pt",
    inferenceTimeMs: 45,
    defaultConfiguration: {
      detectionIntervalMs: 3000,
      maxDetectionsPerFrame: 5,
      alertSeverity: "warning",
      alertCooldownMs: 60000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: true,
  },
  {
    key: "weapon",
    name: "Weapon Detection",
    version: "1.1.0",
    description: "Detects firearms and sharp objects in security feeds.",
    category: "Security",
    icon: "weapon",
    type: "object_detection",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 70,
    gpuSupported: true,
    modelPath: "/models/weapon/weapon.pt",
    inferenceTimeMs: 48,
    defaultConfiguration: {
      detectionIntervalMs: 1000,
      maxDetectionsPerFrame: 10,
      alertSeverity: "critical",
      alertCooldownMs: 10000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: false,
  },
  {
    key: "abandoned_object",
    name: "Abandoned Object Detection",
    version: "1.0.0",
    description: "Flags unattended baggage and suspicious packages.",
    category: "Security",
    icon: "package",
    type: "object_detection",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 60,
    gpuSupported: true,
    modelPath: "/models/abandoned_object/abandoned_object.pt",
    inferenceTimeMs: 42,
    defaultConfiguration: {
      detectionIntervalMs: 2000,
      maxDetectionsPerFrame: 10,
      alertSeverity: "warning",
      alertCooldownMs: 30000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: false,
  },
  {
    key: "ppe",
    name: "PPE Compliance Detection",
    version: "1.0.0",
    description: "Verifies vests, gloves, and protective equipment compliance.",
    category: "Safety",
    icon: "hard-hat",
    type: "object_detection",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 65,
    gpuSupported: true,
    modelPath: "/models/ppe/ppe.pt",
    inferenceTimeMs: 36,
    defaultConfiguration: {
      detectionIntervalMs: 2000,
      maxDetectionsPerFrame: 15,
      alertSeverity: "warning",
      alertCooldownMs: 30000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: false,
  },
  {
    key: "crowd",
    name: "Crowd Density Detection",
    version: "1.0.0",
    description: "Estimates crowd density and flags overcrowding zones.",
    category: "Person",
    icon: "users",
    type: "object_detection",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 55,
    gpuSupported: true,
    modelPath: "/models/crowd/crowd.pt",
    inferenceTimeMs: 28,
    defaultConfiguration: {
      detectionIntervalMs: 2000,
      maxDetectionsPerFrame: 50,
      alertSeverity: "warning",
      alertCooldownMs: 30000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: false,
  },
  {
    key: "violence",
    name: "Violence Detection",
    version: "1.0.0",
    description: "Detects aggressive physical behavior in monitored areas.",
    category: "Behavior",
    icon: "alert-octagon",
    type: "classification",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 75,
    gpuSupported: true,
    modelPath: "/models/violence/violence.pt",
    inferenceTimeMs: 50,
    defaultConfiguration: {
      detectionIntervalMs: 1500,
      maxDetectionsPerFrame: 5,
      alertSeverity: "critical",
      alertCooldownMs: 15000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: false,
  },
  {
    key: "license_plate",
    name: "License Plate Recognition",
    version: "1.0.0",
    description: "Reads vehicle license plates for access control.",
    category: "Vehicle",
    icon: "car",
    type: "object_detection",
    availability: "unconfigured",
    supportedInput: ["image", "video"],
    defaultConfidenceThreshold: 60,
    gpuSupported: true,
    modelPath: "/models/license_plate/license_plate.pt",
    inferenceTimeMs: 44,
    defaultConfiguration: {
      detectionIntervalMs: 2000,
      maxDetectionsPerFrame: 10,
      alertSeverity: "info",
      alertCooldownMs: 60000,
      inputResolution: "640x640",
      processingMode: "auto",
    },
    autoInstall: false,
  },
];

export function registerDefaultDetectors(): void {
  defaultDetectorDefinitions.forEach(registerDetector);
}
