import { registerDetector, type DetectorDefinition } from "./registry";

export const defaultDetectorDefinitions: DetectorDefinition[] = [
  {
    key: "person",
    name: "Person Detection",
    version: "1.0.0",
    description: "Detects persons in camera frames using YOLOv11.",
    category: "Person",
    icon: "person",
    defaultConfidenceThreshold: 50,
    gpuSupported: true,
    modelPath: "/models/person/yolo11n.pt",
    inferenceTimeMs: 24,
    autoInstall: true,
  },
  {
    key: "fire",
    name: "Fire Detection",
    version: "1.0.0",
    description: "Detects fire and open flames in monitored areas.",
    category: "Fire",
    icon: "fire",
    defaultConfidenceThreshold: 45,
    gpuSupported: true,
    modelPath: "/models/fire/fire.pt",
    inferenceTimeMs: 30,
    autoInstall: true,
  },
  {
    key: "smoking",
    name: "Smoking Detection",
    version: "1.0.0",
    description: "Detects smoking activity in restricted areas.",
    category: "Behavior",
    icon: "smoking",
    defaultConfidenceThreshold: 55,
    gpuSupported: true,
    modelPath: "/models/smoking/smoking.pt",
    inferenceTimeMs: 38,
    autoInstall: true,
  },
  {
    key: "helmet",
    name: "Helmet Detection",
    version: "1.0.0",
    description: "Detects workers without protective helmets.",
    category: "Safety",
    icon: "helmet",
    defaultConfidenceThreshold: 60,
    gpuSupported: true,
    modelPath: "/models/helmet/helmet.pt",
    inferenceTimeMs: 32,
    autoInstall: true,
  },
  {
    key: "face_mask",
    name: "Face Mask Detection",
    version: "1.0.0",
    description: "Detects persons without face masks in restricted zones.",
    category: "Safety",
    icon: "face-mask",
    defaultConfidenceThreshold: 55,
    gpuSupported: true,
    modelPath: "/models/face_mask/face_mask.pt",
    inferenceTimeMs: 26,
    autoInstall: true,
  },
  {
    key: "vehicle",
    name: "Vehicle Detection",
    version: "1.0.0",
    description: "Detects cars, trucks, and motorcycles in traffic zones.",
    category: "Vehicle",
    icon: "vehicle",
    defaultConfidenceThreshold: 50,
    gpuSupported: true,
    modelPath: "/models/vehicle/vehicle.pt",
    inferenceTimeMs: 34,
    autoInstall: true,
  },
  {
    key: "intrusion",
    name: "Intrusion Detection",
    version: "1.0.0",
    description: "Detects unauthorized entry into restricted zones.",
    category: "Security",
    icon: "intrusion",
    defaultConfidenceThreshold: 65,
    gpuSupported: true,
    modelPath: "/models/intrusion/intrusion.pt",
    inferenceTimeMs: 40,
    autoInstall: true,
  },
  {
    key: "drowsiness",
    name: "Drowsiness Detection",
    version: "1.0.0",
    description: "Detects operator drowsiness and fatigue signs.",
    category: "Behavior",
    icon: "drowsiness",
    defaultConfidenceThreshold: 60,
    gpuSupported: true,
    modelPath: "/models/drowsiness/drowsiness.pt",
    inferenceTimeMs: 45,
    autoInstall: true,
  },
  {
    key: "weapon",
    name: "Weapon Detection",
    version: "1.1.0",
    description: "Detects firearms and sharp objects in security feeds.",
    category: "Security",
    icon: "weapon",
    defaultConfidenceThreshold: 70,
    gpuSupported: true,
    modelPath: "/models/weapon/weapon.pt",
    inferenceTimeMs: 48,
    autoInstall: false,
  },
  {
    key: "abandoned_object",
    name: "Abandoned Object Detection",
    version: "1.0.0",
    description: "Flags unattended baggage and suspicious packages.",
    category: "Security",
    icon: "package",
    defaultConfidenceThreshold: 60,
    gpuSupported: true,
    modelPath: "/models/abandoned_object/abandoned_object.pt",
    inferenceTimeMs: 42,
    autoInstall: false,
  },
  {
    key: "ppe",
    name: "PPE Compliance Detection",
    version: "1.0.0",
    description: "Verifies vests, gloves, and protective equipment compliance.",
    category: "Safety",
    icon: "hard-hat",
    defaultConfidenceThreshold: 65,
    gpuSupported: true,
    modelPath: "/models/ppe/ppe.pt",
    inferenceTimeMs: 36,
    autoInstall: false,
  },
  {
    key: "crowd",
    name: "Crowd Density Detection",
    version: "1.0.0",
    description: "Estimates crowd density and flags overcrowding zones.",
    category: "Person",
    icon: "users",
    defaultConfidenceThreshold: 55,
    gpuSupported: true,
    modelPath: "/models/crowd/crowd.pt",
    inferenceTimeMs: 28,
    autoInstall: false,
  },
  {
    key: "violence",
    name: "Violence Detection",
    version: "1.0.0",
    description: "Detects aggressive physical behavior in monitored areas.",
    category: "Behavior",
    icon: "alert-octagon",
    defaultConfidenceThreshold: 75,
    gpuSupported: true,
    modelPath: "/models/violence/violence.pt",
    inferenceTimeMs: 50,
    autoInstall: false,
  },
  {
    key: "license_plate",
    name: "License Plate Recognition",
    version: "1.0.0",
    description: "Reads vehicle license plates for access control.",
    category: "Vehicle",
    icon: "car",
    defaultConfidenceThreshold: 60,
    gpuSupported: true,
    modelPath: "/models/license_plate/license_plate.pt",
    inferenceTimeMs: 44,
    autoInstall: false,
  },
];

export function registerDefaultDetectors(): void {
  defaultDetectorDefinitions.forEach(registerDetector);
}
